# Generated by Django 4.1.1 on 2022-10-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blockchain', models.CharField(max_length=100)),
                ('floor_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('num_of_sales', models.IntegerField()),
                ('num_of_holders', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
