# Generated by Django 4.1.1 on 2022-10-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tx_hash',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
