# Generated by Django 4.1.1 on 2022-10-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0002_collection_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='tx_hash',
            field=models.CharField(max_length=100),
        ),
    ]
