# Generated by Django 4.1.1 on 2022-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0004_alter_collection_floor_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='blockchain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='floor_price',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='max_price',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='num_of_holders',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='num_of_sales',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
