# Generated by Django 4.1.1 on 2022-10-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0006_alter_collection_blockchain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='tx_hash',
            new_name='address',
        ),
    ]
