# Generated by Django 4.1.1 on 2022-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0007_rename_tx_hash_collection_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_web_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='discord_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
