# Generated by Django 4.1.2 on 2022-10-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0008_collection_collection_web_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='abacus_deployment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
