# Generated by Django 4.1.2 on 2022-10-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0009_collection_abacus_deployment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='link',
            new_name='search_link',
        ),
    ]
