# Generated by Django 4.1.2 on 2022-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0010_rename_link_collection_search_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='open_sea_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
