# Generated by Django 4.1.2 on 2022-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NftDashboard", "0014_alter_nft_asset_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="asset_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
