# Generated by Django 4.1.2 on 2022-11-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0016_nft_collection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='asset_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
