# Generated by Django 4.1.2 on 2022-11-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NftDashboard', '0017_alter_nft_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='asset_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
